name: Build and Release PixelOS ROM

on: workflow_dispatch

env:
  REPO_USE_SSH: "true"
  CCACHE_SIZE: "5G"

jobs:
  PixelOS:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Check Disk Space
        run: |
          df -h
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android/sdk/ndk-bundle || true

      - name: Cleanup
        run: |
          rm -rf ${{ github.workspace }}/*
          sudo rm -rf /var/lib/apt/lists/*

      - name: Install Dependencies (Optimized)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends bc bison build-essential curl flex git gnupg gperf libncurses-dev libssl-dev libxml2 libxml2-utils lzop pngcrush squashfs-tools xsltproc zip zlib1g-dev gcc-multilib g++-multilib lib32z1-dev python3 python3-pip openjdk-17-jdk repo unzip
          sudo apt-get clean

      - name: Setup Swap
        run: |
          sudo fallocate -l 8G /swapfile  # Reducido de 16G a 8G
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Setup Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize ROM Source
        run: |
          mkdir rom && cd rom
          repo init -u https://github.com/PixelOS-Fifteen/manifest.git -b fifteen --depth=1

      - name: Sync ROM Source (Optimized)
        run: |
          cd rom
          repo sync -c --no-clone-bundle --no-tags --optimized-fetch --force-sync -j$(nproc --all) --prune

      - name: Clone Device Trees
        run: |
          cd rom
          git clone https://github.com/adamspaini/device_xiaomi_vayu.git device/xiaomi/vayu
          git clone https://github.com/adamspaini/kernel_xiaomi_vayu_A16.git -b 16 kernel/xiaomi/sm8150
          git clone https://github.com/adamspaini/vendor_xiaomi_vayu-blaze.git vendor/xiaomi
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9

      - name: Build ROM
        run: |
          cd rom
          source build/envsetup.sh
          lunch aosp_vayu-userdebug
          export CCACHE_DIR=$GITHUB_WORKSPACE/ccache
          export CCACHE_EXEC=$(which ccache)
          export USE_CCACHE=1
          ccache -o compression=true
          mka bacon -j$(($(nproc --all)/2))

      - name: Check build artifacts
        run: |
          cd rom
          if [ -d "out/target/product/vayu" ]; then
            zip_file=$(find out/target/product/vayu -maxdepth 1 -iname '*.zip' -print -quit)
            if [ -n "$zip_file" ]; then
              echo "ZIP_FILE=$zip_file" >> $GITHUB_ENV
              echo "ZIP_NAME=$(basename $zip_file .zip)" >> $GITHUB_ENV
            else
              echo "No se encontr칩 archivo ZIP en la salida"
              exit 1
            fi
          else
            echo "No se encontr칩 el directorio de salida"
            exit 1
          fi

      - name: Upload ROM to Releases
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: ${{ env.ZIP_FILE }}
          name: ${{ env.ZIP_NAME }}
          tag_name: build-${{ github.run_id }}
          body: |
            PixelOS for vayu (Poco X3 Pro)
            Compilaci칩n autom치tica - CircleCi
            Android 15 - PixelOS
            Build ID: ${{ github.run_id }}

      - name: Cleanup Swap
        if: always()
        run: |
          sudo swapoff /swapfile || true
          sudo rm -f /swapfile || true
