name: Build and Release Kernel

on:
  workflow_dispatch:

jobs:
  Kernel:
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: bash
       working-directory: ${{ github.workspace }}

    steps:
      - name: Cleanup
        run: rm -rf ${{ github.workspace }}/build_output*

      - name: Set up swap
        run: |
          sudo fallocate -l 16G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon --priority 10 /swapfile

      - name: Update system
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc

      - name: Clone kernel source
        run: git clone https://github.com/adamspaini/kernel_vayu_sm8150_.git -b fiveteen --depth=1 .

      - name: Install required packages
        run: sudo apt-get install -y $(cat tools/build/packages.txt)

      - name: Start Compilation
        run: bash tools/build/build.sh

      - name: Set-up files
        run: |
          output_dir="${{ github.workspace }}/output"
          mkdir -p "$output_dir"
          zip_file=$(find "$output_dir" -name 'Gorekernel_vayu*.zip' -print -quit)
          echo "ZIP_FILE=$zip_file" >> $GITHUB_ENV
          echo "ZIP_NAME=$(basename "$zip_file" .zip)" >> $GITHUB_ENV

      - name: Upload files to repository releases page
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ZIP_FILE }}
          name: ${{ env.ZIP_NAME }}
          tag_name: ${{ github.run_id }}
          body: |
            Non KernelSU